---
title: "IA-SVA Examples"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: true
---

## Real scRNA-Seq Studies
* [Example 1) Detecting hidden heterogeneity in human islet alpha cells](detecting_hidden_heterogeneity.html)
* [Example 2) Detecting cell-cycle stage difference in glioblastoma cells](hidden_heterogeneity_glioblastoma.html)
* [Example 3) IA-SVA based feature selection improves the performance of clustering algorithms (1)](tSNE_post_IA-SVA_3celltypes.html)
* [Example 4) IA-SVA based feature selection improves the performance of clustering algorithms (2)](tSNE_post_IA-SVA_Xin_Iselts.html)


## Simulation Studies
* [Example 5) Compare IA-SVA to factor analyses methods in terms of their ability to detect marker genes for different cell types](Brain_scRNASeq_neuron_vs_oligodendrocyte_single_run.html)
* [Example 6) scRNA-seq Data Simulation (1)](scRNAseq_simulation.html)
* [Example 7) scRNA-seq Data Simulation (2)](sim_study_KF_HF_genes_overlap.html)

## Reviewer #2 Simulations
* [Reviewer #2's Simulations](reviewer2_sim.html)
* [Suggested Simulations](reviewer2_sim_suggested.html)
